------------------------------------------------------------
-- FRAGMENTO F4  (NODO S2)
------------------------------------------------------------

-- Catálogo de sucursales
CREATE TABLE SUCURSAL_F4_SAKCC_S2 (
  SUCURSAL_ID  NUMBER(10,0)    NOT NULL,
  CLAVE        VARCHAR2(10)    NOT NULL,
  ES_TALLER    NUMBER(1,0)     NOT NULL,   -- BIT
  ES_VENTA     NUMBER(1,0)     NOT NULL,   -- BIT
  NOMBRE       VARCHAR2(40)    NOT NULL,
  LATITUD      NUMBER          NOT NULL,
  LONGITUD     NUMBER          NOT NULL,
  URL          VARCHAR2(200)   NOT NULL,
  CONSTRAINT PK_SUCURSAL_F4_SAKCC_S2
    PRIMARY KEY (SUCURSAL_ID)
);

-- Datos adicionales cuando la sucursal es taller
CREATE TABLE SUCURSAL_TALLER_F4_SAKCC_S2 (
  SUCURSAL_ID        NUMBER(10,0)  NOT NULL,
  DIA_DESCANSO       NUMBER(1,0)   NOT NULL,
  TELEFONO_ATENCION  VARCHAR2(20)  NOT NULL,
  CONSTRAINT PK_SUCURSAL_TALLER_F4_SAKCC_S2
    PRIMARY KEY (SUCURSAL_ID),
  CONSTRAINT FK_STALLER_F4_SUCURSAL_F4_S2
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_SAKCC_S2 (SUCURSAL_ID)
);

-- Datos adicionales cuando la sucursal es de venta
CREATE TABLE SUCURSAL_VENTA_F4_SAKCC_S2 (
  SUCURSAL_ID   NUMBER(10,0)  NOT NULL,
  HORA_APERTURA DATE          NOT NULL,
  HORA_CIERRE   DATE          NOT NULL,
  CONSTRAINT PK_SUCURSAL_VENTA_F4_SAKCC_S2
    PRIMARY KEY (SUCURSAL_ID),
  CONSTRAINT FK_SVENTA_F4_SUCURSAL_F4_S2
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_SAKCC_S2 (SUCURSAL_ID)
);

-- Catálogos de tipos
CREATE TABLE TIPO_PROCESADOR_F4_SAKCC_S2 (
  TIPO_PROCESADOR_ID  NUMBER(5,0)   NOT NULL,
  CLAVE               VARCHAR2(40)  NOT NULL,
  DESCRIPCION         VARCHAR2(400) NOT NULL,
  CONSTRAINT PK_TIPO_PROCESADOR_F4_SAKCC_S2
    PRIMARY KEY (TIPO_PROCESADOR_ID)
);

CREATE TABLE TIPO_TARJETA_F4_SAKCC_S2 (
  TIPO_TARJETA_VIDEO  VARCHAR2(5)   NOT NULL,
  CLAVE               VARCHAR2(40)  NOT NULL,
  DESCRIPCION         VARCHAR2(400) NOT NULL,
  CONSTRAINT PK_TIPO_TARJETA_F4_SAKCC_S2
    PRIMARY KEY (TIPO_TARJETA_VIDEO)
);

CREATE TABLE TIPO_ALMACENAMIENTO_F4_SAKCC_S2 (
  TIPO_ALMACENAMIENTO_ID  NUMBER(5,0)   NOT NULL,
  CLAVE                   VARCHAR2(40)  NOT NULL,
  "DESC"                  VARCHAR2(400) NOT NULL,
  CONSTRAINT PK_TIPO_ALMACENAMIENTO_F4_SAKCC_S2
    PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
);

CREATE TABLE TIPO_MONITOR_F4_SAKCC_S2 (
  TIPO_MONITOR_ID  NUMBER(5,0)   NOT NULL,
  CLAVE            VARCHAR2(40)  NOT NULL,
  DESCRIPCION      VARCHAR2(400) NOT NULL,
  CONSTRAINT PK_TIPO_MONITOR_F4_SAKCC_S2
    PRIMARY KEY (TIPO_MONITOR_ID)
);

-- Catálogo de estatus de laptop
CREATE TABLE STATUS_LAPTOP_F4_SAKCC_S2 (
  STATUS_LAPTOP_ID  NUMBER(10,0)   NOT NULL,
  CLAVE             VARCHAR2(40)   NOT NULL,
  DESCRIPCION       VARCHAR2(400)  NOT NULL,
  CONSTRAINT PK_STATUS_LAPTOP_F4_SAKCC_S2
    PRIMARY KEY (STATUS_LAPTOP_ID)
);

-- Laptop
CREATE TABLE LAPTOP_F4_SAKCC_S2 (
  LAPTOP_ID              NUMBER(10,0)   NOT NULL,
  LAPTOP_REEMPLAZO_ID    NUMBER(10,0),          -- FK opcional a LAPTOP_F4_SAKCC_S2
  NUM_SERIE              VARCHAR2(18)   NOT NULL,
  CANTIDAD_RAM           NUMBER(4,0)    NOT NULL,
  CARACTERISTICAS_EXTRAS VARCHAR2(2000) NOT NULL,
  TIPO_PROCESADOR_ID     NUMBER(5,0)    NOT NULL,
  TIPO_TARJETA_VIDEO     VARCHAR2(5)    NOT NULL,
  TIPO_ALMACENAMIENTO_ID NUMBER(5,0)    NOT NULL,
  TIPO_MONITOR_ID        NUMBER(5,0)    NOT NULL,
  SUCURSAL_ID            NUMBER(10,0)   NOT NULL,
  CONSTRAINT PK_LAPTOP_F4_SAKCC_S2
    PRIMARY KEY (LAPTOP_ID),
  CONSTRAINT FK_LAPTOP_F4_LAPTOP_REEMP
    FOREIGN KEY (LAPTOP_REEMPLAZO_ID)
    REFERENCES LAPTOP_F4_SAKCC_S2 (LAPTOP_ID),
  CONSTRAINT FK_LAPTOP_F4_TPROC_F4_S2
    FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR_F4_SAKCC_S2 (TIPO_PROCESADOR_ID),
  CONSTRAINT FK_LAPTOP_F4_TTARJ_F4_S2
    FOREIGN KEY (TIPO_TARJETA_VIDEO)
    REFERENCES TIPO_TARJETA_F4_SAKCC_S2 (TIPO_TARJETA_VIDEO),
  CONSTRAINT FK_LAPTOP_F4_TALM_F4_S2
    FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO_F4_SAKCC_S2 (TIPO_ALMACENAMIENTO_ID),
  CONSTRAINT FK_LAPTOP_F4_TMON_F4_S2
    FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR_F4_SAKCC_S2 (TIPO_MONITOR_ID),
  CONSTRAINT FK_LAPTOP_F4_SUCURSAL_F4_S2
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_SAKCC_S2 (SUCURSAL_ID)
);

-- Servicio de reparación de laptops
CREATE TABLE SERVICIO_LAPTOP_F4_SAKCC_S2 (
  NUM_SERVICIO  NUMBER(10,0)   NOT NULL,
  LAPTOP_ID     NUMBER(10,0)   NOT NULL,
  IMPORTE       NUMBER(8,2)    NOT NULL,
  DIAGNOSTICO   VARCHAR2(2000) NOT NULL,
  FACTURA       BLOB,
  SUCURSAL_ID   NUMBER(10,0)   NOT NULL,
  CONSTRAINT PK_SERVICIO_LAPTOP_F4_SAKCC_S2
    PRIMARY KEY (NUM_SERVICIO),
  CONSTRAINT FK_SRV_LAPTOP_F4_LAPTOP_F4_S2
    FOREIGN KEY (LAPTOP_ID)
    REFERENCES LAPTOP_F4_SAKCC_S2 (LAPTOP_ID),
  CONSTRAINT FK_SRV_LAPTOP_F4_SUCURSAL_F4_S2
    FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F4_SAKCC_S2 (SUCURSAL_ID)
);

-- Foto asociada a la laptop
CREATE TABLE LAPTOP_FOTO_F1_SAKCC_S2 (
  LAPTOP_ID  NUMBER(10,0)  NOT NULL,
  FOTO       BLOB          NOT NULL,
  CONSTRAINT PK_LAPTOP_FOTO_F1_SAKCC_S2
    PRIMARY KEY (LAPTOP_ID),
  CONSTRAINT FK_LAPTOP_FOTO_F1_LAPTOP_F4_S2
    FOREIGN KEY (LAPTOP_ID)
    REFERENCES LAPTOP_F4_SAKCC_S2 (LAPTOP_ID)
);
