SET SQLBLANKLINES ON;
SET DEFINE OFF;

------------------------------------------------------------
-- CREACIÓN DE TABLAS (FRAGMENTO F3 / NODO S1)
------------------------------------------------------------

-- Catálogo de sucursales
CREATE TABLE SUCURSAL_F3_SAKCC_S1 (
  SUCURSAL_ID  NUMBER(10)    NOT NULL,
  CLAVE        VARCHAR2(10)  NOT NULL,
  ES_TALLER    NUMBER(1)     NOT NULL,   
  ES_VENTA     NUMBER(1)     NOT NULL,   
  NOMBRE       VARCHAR2(40)  NOT NULL,
  LATITUD      FLOAT         NOT NULL,
  LONGITUD     FLOAT         NOT NULL,
  URL          VARCHAR2(200) NOT NULL,
  CONSTRAINT PK_SUCURSAL_F3_SAKCC_S1 PRIMARY KEY (SUCURSAL_ID)
);

-- Datos de taller
CREATE TABLE SUCURSAL_TALLER_F3_SAKCC_S1 (
  SUCURSAL_ID        NUMBER(10)   NOT NULL,
  DIA_DESCANSO       NUMBER(1)    NOT NULL,
  TELEFONO_ATENCION  VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_SUCURSAL_TALLER_F3_SAKCC_S1 PRIMARY KEY (SUCURSAL_ID),
  CONSTRAINT FK_STALLER_F3_SUCURSAL_F3_S1 FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL_F3_SAKCC_S1 (SUCURSAL_ID)
);

-- Datos de venta
CREATE TABLE SUCURSAL_VENTA_F3_SAKCC_S1 (
  SUCURSAL_ID   NUMBER(10) NOT NULL,
  HORA_APERTURA DATE       NOT NULL,
  HORA_CIERRE   DATE       NOT NULL,
  CONSTRAINT PK_SUCURSAL_VENTA_F3_SAKCC_S1 PRIMARY KEY (SUCURSAL_ID),
  CONSTRAINT FK_SVENTA_F3_SUCURSAL_F3_S1 FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL_F3_SAKCC_S1 (SUCURSAL_ID)
);

-- Catálogos de tipos
CREATE TABLE TIPO_PROCESADOR_R_SAKCC_S1 (
  TIPO_PROCESADOR_ID  NUMBER(5,0)   NOT NULL,
  CLAVE               VARCHAR2(40)  NOT NULL,
  DESCRIPCION         VARCHAR2(400) NOT NULL,
  CONSTRAINT PK_TIPO_PROCESADOR_R_SAKCC_S1 PRIMARY KEY (TIPO_PROCESADOR_ID)
);

CREATE TABLE TIPO_TARJETA_VIDEO_R_SAKCC_S1 (
  TIPO_TARJETA_VIDEO_ID     NUMBER(5,0)   NOT NULL,
  CLAVE               VARCHAR2(40)  NOT NULL,
  DESCRIPCION         VARCHAR2(400) NOT NULL,
  CONSTRAINT PK_TIPO_TARJETA_VIDEO_R_SAKCC_S1 PRIMARY KEY (TIPO_TARJETA_VIDEO_ID)
);

CREATE TABLE TIPO_ALMACENAMIENTO_R_SAKCC_S1 (
  TIPO_ALMACENAMIENTO_ID         NUMBER(5,0)   NOT NULL,
  CLAVE               VARCHAR2(40)  NOT NULL,
  DESCRIPCION         VARCHAR2(400) NOT NULL,
  CONSTRAINT PK_TIPO_ALM_R_SAKCC_S1 PRIMARY KEY (TIPO_ALMACENAMIENTO_ID)
);

CREATE TABLE TIPO_MONITOR_R_SAKCC_S1 (
  TIPO_MONITOR_ID     NUMBER(5,0)   NOT NULL,
  CLAVE               VARCHAR2(40)  NOT NULL,
  DESCRIPCION         VARCHAR2(400) NOT NULL,
  CONSTRAINT PK_TIPO_MONITOR_R_SAKCC_S1 PRIMARY KEY (TIPO_MONITOR_ID)
);

-- Catálogo de estatus de laptop
CREATE TABLE status_laptop (
  status_laptop_id  NUMBER(5,0)   NOT NULL,
  clave             VARCHAR2(40)  NOT NULL,
  descripcion       VARCHAR2(400) NOT NULL,
  CONSTRAINT pk_status_laptop PRIMARY KEY (status_laptop_id)
);

-- Laptop (AQUÍ ESTABAN LOS ERRORES PRINCIPALES)
CREATE TABLE LAPTOP_F3_SAKCC_S1 (
  LAPTOP_ID              NUMBER(10,0)   NOT NULL,
  LAPTOP_REEMPLAZO_ID    NUMBER(10,0),
  NUM_SERIE              VARCHAR2(18)   NOT NULL,
  CANTIDAD_RAM           NUMBER(10)     NOT NULL,
  CARACTERISTICAS_EXTRAS VARCHAR2(4000) NULL,
  TIPO_PROCESADOR_ID     NUMBER(10)     NOT NULL,
  TIPO_TARJETA_VIDEO_ID  NUMBER(10)     NOT NULL,
  TIPO_ALMACENAMIENTO_ID NUMBER(10)     NOT NULL,
  TIPO_MONITOR_ID        NUMBER(10)     NOT NULL,
  CONSTRAINT PK_LAPTOP_F3_SAKCC_S1 PRIMARY KEY (LAPTOP_ID),
  --CONSTRAINT FK_LAPTOP_F3_LAPTOP_REEMP FOREIGN KEY (LAPTOP_REEMPLAZO_ID) REFERENCES LAPTOP_F3_SAKCC_S1 (LAPTOP_ID),
  CONSTRAINT FK_LAPTOP_F3_TPROC_F3_S1 FOREIGN KEY (TIPO_PROCESADOR_ID) REFERENCES TIPO_PROCESADOR_R_SAKCC_S1 (TIPO_PROCESADOR_ID),
  -- Corrección 1 aplicada: Sin lineas en blanco
  CONSTRAINT FK_LAPTOP_F3_TTARJ_F3_S1 FOREIGN KEY (TIPO_TARJETA_VIDEO_ID) REFERENCES TIPO_TARJETA_VIDEO_R_SAKCC_S1 (TIPO_TARJETA_VIDEO_ID),
  -- Corrección 2 aplicada: Sin lineas en blanco
  CONSTRAINT FK_LAPTOP_F3_TALM_F3_S1 FOREIGN KEY (TIPO_ALMACENAMIENTO_ID) REFERENCES TIPO_ALMACENAMIENTO_R_SAKCC_S1 (TIPO_ALMACENAMIENTO_ID),
  CONSTRAINT FK_LAPTOP_F3_TMON_F3_S1 FOREIGN KEY (TIPO_MONITOR_ID) REFERENCES TIPO_MONITOR_R_SAKCC_S1 (TIPO_MONITOR_ID)
);

-- Inventario: relación con cliente / tarjeta
CREATE TABLE LAPTOP_INVENTARIO_F2_SAKCC_S1 (
  LAPTOP_ID    NUMBER(10)   NOT NULL,
  RFC_CLIENTE  VARCHAR2(13) NOT NULL,
  NUM_TARJETA  VARCHAR2(16) NOT NULL,
  CONSTRAINT PK_LAPTOP_INVENTARIO_F2_SAKCC_S1 PRIMARY KEY (LAPTOP_ID),
  CONSTRAINT FK_LAPTOP_INV_F2_LAPTOP_F3_S1 FOREIGN KEY (LAPTOP_ID) REFERENCES LAPTOP_F3_SAKCC_S1 (LAPTOP_ID)
);

-- Servicio de reparación de laptops
CREATE TABLE SERVICIO_LAPTOP_F3_SAKCC_S1 (
  NUM_SERVICIO  NUMBER(10)     NOT NULL,
  LAPTOP_ID     NUMBER(10)     NOT NULL,
  IMPORTE       NUMBER(8,2)    NOT NULL,
  DIAGNOSTICO   VARCHAR2(2000) NOT NULL,
  FACTURA       BLOB,
  SUCURSAL_ID   NUMBER(10)     NOT NULL,
  CONSTRAINT PK_SERVICIO_LAPTOP_F3_SAKCC_S1 PRIMARY KEY (NUM_SERVICIO, LAPTOP_ID),
  CONSTRAINT FK_SRV_LAPTOP_F3_LAPTOP_F3_S1 FOREIGN KEY (LAPTOP_ID) REFERENCES LAPTOP_INVENTARIO_F2_SAKCC_S1 (LAPTOP_ID),
  CONSTRAINT FK_SRV_LAPTOP_F3_SUCURSAL_F3_S1 FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL_F3_SAKCC_S1 (SUCURSAL_ID)
);
